language: r
r:
  - release
  - oldrel
#  - devel
sudo: required
dist: trusty
before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  # units/udunits2 dependency:
  - sudo apt-get install --yes libudunits2-dev
  # sf dependencies:
  - sudo apt-get install --yes libproj-dev libgeos-dev libgdal-dev
r_packages:
  - sf
  - testthat
r_github_packages: 
  - jimhester/covr
after_success:
  - Rscript -e 'covr::codecov()'
