language: r
sudo: required
dist: trusty
apt_packages:
  - gdal-bin
  - libgdal1-dev
  - libproj-dev
r_packages:
  - rgdal
  - testthat
r_github_packages: 
  - jimhester/covr
after_success:
  - Rscript -e 'covr::codecov()'
